version: "3.9.7"

services:
  web:
    build: .
    command: sh -c "python manage.py migrate --skip-checks &&
      python manage.py loaddata fixtures/initial_data.json &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"