# Generated by Django 4.0.4 on 2022-05-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.ManyToManyField(blank=True, to="payment.discount"),
        ),
        migrations.AlterField(
            model_name="order",
            name="tax",
            field=models.ManyToManyField(blank=True, to="payment.tax"),
        ),
    ]
